version: "3.6"

services:
  worker:
    build: .
    image: ghcr.io/duhow/qt:latest
    restart: always
    hostname: worker
    privileged: true
    tty: true
    stdin_open: true
    cap_add:
        - SYS_PTRACE
        - SYS_ADMIN
    ulimits:
      nproc: 655353
      nofile:
        soft: 20000
        hard: 40000
    tmpfs:
      - /tmp:exec,mode=1777
    volumes:
      - ./volumes/repo:/home/myuser/repo
      - ./volumes/conan:/home/myuser/.conan/data
    ports:
      - "2222:22"
