name: Release

on:
  push:
    tags:
    - '**'
    branches:
    - master

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux Static
          file: Dockerfile.static
          tag: 5.15.9-static
          build-args: |
            QT_VERSION=5.15.9

        - name: Linux Dynamic
          file: Dockerfile
          tag: 6-dynamic

        - name: MXE Win32 Static
          file: Dockerfile.mxe
          tag: 6-static-win32
          build-args: |
            MXE_ARCH=i686
            MXE_BUILD=static
        - name: MXE Win32 Dynamic
          file: Dockerfile.mxe
          tag: 6-dynamic-win32
          build-args: |
            MXE_ARCH=i686
            MXE_BUILD=shared

        - name: MXE Win64 Static
          file: Dockerfile.mxe
          tag: 6-static-win64
          build-args: |
            MXE_ARCH=x86_64
            MXE_BUILD=static
        - name: MXE Win64 Dynamic
          file: Dockerfile.mxe
          tag: 6-dynamic-win64
          build-args: |
            MXE_ARCH=x86_64
            MXE_BUILD=shared
    name: ${{ matrix.name }}
    uses: ./.github/workflows/build.yaml
    with:
      file: ${{ matrix.file }}
      tag: ${{ matrix.tag }}
